spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: cn.bdqn.guli.entity
  mapper-locations: classpath:mapper/**.xml
  configuration:
    cache-enabled: true
spring:
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
    username: root
    password:
  profiles:
    active: dev

##将服务注册到eureka服务列表中 1231
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: mumu-onfig
    prefer-ip-address: true
info:
  app.name: bdqn-mumu
  company.name: mumuconfig
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"



---
server:
  port: 8002
mybatis:
  type-aliases-package: cn.bdqn.guli.entity
  mapper-locations: classpath:mapper/**.xml
  configuration:
    cache-enabled: true
spring:
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
    username: root
    password:
  profiles:
    active: test

##将服务注册到eureka服务列表中
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: mumu-test
    prefer-ip-address: true
info:
  app.name: bdqn-mumu
  company.name: mumutest
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
